### ISSUE TITLE
Виджет неверно считает значение высоты в модуле

### ISSUE THREAD

**Issue by sashabeep** [webber12/CommerceCoupons#1]
Часть содержимого обрезается на последней строке
Firefox
![Снимок экрана 2020-04-14 в 14 41 59](https://user-images.githubusercontent.com/5689796/79221226-1d310980-7e5e-11ea-8fcd-9fbb0509bd96.png)

**Comment by webber12** [comment]
Странно, у меня такое нашлось только на темной теме за счет того, что для заголовка были разные отступы в темной и светлой теме. Попробуй:
1. перейти на локальные файлы - https://github.com/webber12/CommerceCoupons/commit/b1523cde66126ff48a40789cf2f3bf43543ae1eb - а то cdn-версия у них в последнее время глючит 
2. пофиксить разные отступы для тем в общем модуле - https://github.com/webber12/webixtable/commit/c477915173dc24a50e2d5bd5693dbf57f01bc981 

У меня после этого в хроме и фф все вроде норм.

**Comment by sashabeep** [comment]
Yup, стили улучшились, как минимум, значки встали посередине кнопок, обрезка убралась после этих изменений
