### ISSUE TITLE
Купон применяется, но цена не пересчитывается

### ISSUE THREAD

**Issue by sashabeep** [webber12/CommerceCoupons#2]
Такие сообщения в консоли

![Снимок экрана 2020-04-14 в 14 41 18](https://user-images.githubusercontent.com/5689796/79221282-35a12400-7e5e-11ea-9e24-958aebdbe714.png)

**Comment by sashabeep** [comment]
Поменял функцию, варнинг от commerce пропал, пишет commerce-coupon-ok-add, сумма не пересчитывается

**Comment by webber12** [comment]
с uploadCarts() я вижу цена меняется, просто корзина не перегружается. После обновления там уже норм цена. Наверно что-то опять поменялось в commerce с js :)

**Comment by webber12** [comment]
fix на уровне commerce - https://github.com/mnoskov/commerce/commit/4ee46f77e33c995d8b89e577fe22bd33fc8f31ba

**Comment by sashabeep** [comment]
@webber12 fixed
